version: '2'

volumes:
  mysql_data_dev: {}
  mysql_backup_dev: {}

services:
  mysql:
    build: ./compose/mysql
    volumes:
      - mysql_data_dev:/var/lib/mysql/data
      - mysql_backup_dev:/backups
    environment:
      - MYSQL_USER=paiba

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - mysql
    environment:
      - MYSQL_USER=paiba
      - USE_DOCKER=yes
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    links:
      - mysql
