# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-22 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'male'), ('W', 'female'), ('U', 'unknown')], default='U', max_length=8, verbose_name='Gender'),
        ),
        migrations.AddField(
            model_name='user',
            name='portrait',
            field=models.ImageField(default='U', upload_to='portraits/', verbose_name='Portrait'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=127, verbose_name='Nickname of User'),
        ),
    ]
